name: 4.1 Main Workflow CI/CD for Develop

on: 
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:

  ci_dev:
    name: Run CI Workflow for Dev
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/ci.yml
    with:
      branch: develop
      environment: develop
    secrets: inherit

  cd_dev:
    name: Run CD Workflow for Dev
    needs: ci_dev
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/cd-deploy-aks.yml
    with:
      version: ${{ needs.ci_dev.outputs.version }}
      repository: ${{ needs.ci_dev.outputs.repository }}
      environment: develop
    secrets: inherit

  # deploy_dev:
  #   name: Deploy to Kubernetes with Helm
  #   needs: cd_dev
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Install Helm
  #       run: |
  #         curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
  #     - name: Set up Helm
  #       uses: azure/setup-helm@v1
  #       with:
  #         version: v3.7.1
        
  #     - name: Create .kube directory
  #       run: mkdir -p $HOME/.kube
  
  #     - name: Configure kubectl
  #       run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
  #       shell: bash

  #     - name: Verify Kubernetes connection
  #       env:
  #         KUBECONFIG: $HOME/.kube/config
  #       run: kubectl cluster-info

  #     - name: Deploy with Helm
  #       env:
  #         HELM_EXPERIMENTAL_OCI: 1
  #         KUBECONFIG: $HOME/.kube/config
  #       run: |
  #         helm upgrade --install my-application ./kubernetes/my-application \
  #           --values ./kubernetes/my-application/values-dev.yaml \
  #           --namespace ns-plopez
      
  #     - name: Set kubeconfig file permissions
  #       run: chmod 600 $HOME/.kube/config
    